import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { drizzle } from "drizzle-orm/node-postgres";
import type { PoolClient } from "pg";

import { createPostgresPool } from "../../db-client";
import { FinanceExpenseServiceError } from "../../financeExpenseService";
import {
  applyFinancePaymentToBill,
  createFinanceBill,
  createFinanceReconciliationException,
  createFinanceVendor,
  financeBillResponse,
  getFinanceOverview,
  listFinanceBills,
  listFinancePaymentLedger,
  listFinancePayments,
  recordPaidFinanceBill,
  approveAndRecordFinanceBillPayment,
  recordFinanceBillPayment,
  recordFinancePayment,
  transitionFinanceBillStatus,
  transitionFinanceReconciliationException,
} from "../../financeExpenseService";
import { createFinanceExpenseRepository } from "../../financeExpenseRepositoryFactory";

const POSTGRES_TEST_DATABASE_URL = process.env.MIGRATION_RUNNER_TEST_DATABASE_URL;

function assertDisposablePostgresTestUrl(connectionString: string) {
  let databaseName = "";
  try {
    const parsed = new URL(connectionString.replace(/^postgres:\/\//, "postgresql://"));
    databaseName = decodeURIComponent(parsed.pathname.replace(/^\//, ""));
  } catch {
    throw new Error("MIGRATION_RUNNER_TEST_DATABASE_URL must be a valid PostgreSQL URL.");
  }

  if (!/(test|tmp|scratch|disposable|codex)/i.test(databaseName)) {
    throw new Error(
      "MIGRATION_RUNNER_TEST_DATABASE_URL must point to a disposable database whose name contains test, tmp, scratch, disposable, or codex.",
    );
  }
}

function testSchemaName() {
  return `stage5_ap_${process.pid}_${crypto.randomUUID().replace(/-/g, "").slice(0, 12)}`;
}

async function createApTables(client: PoolClient) {
  await client.query(`
    CREATE TABLE "legal_entities" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "legal_name" text NOT NULL,
      "entity_type" text NOT NULL DEFAULT 'llc',
      "formation_state" text,
      "masked_tax_identifier" text,
      "status" text NOT NULL DEFAULT 'active',
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "vendors" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "name" text NOT NULL,
      "vendor_type" text NOT NULL DEFAULT 'other',
      "status" text NOT NULL DEFAULT 'active',
      "website" text,
      "contact_email" text,
      "notes" text,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "recurring_expenses" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "legal_entity_id" integer NOT NULL,
      "vendor_id" integer NOT NULL,
      "name" text NOT NULL,
      "category_code" text NOT NULL,
      "cadence" text NOT NULL,
      "expected_amount_cents" integer,
      "currency" text NOT NULL DEFAULT 'USD',
      "variable_amount" boolean NOT NULL DEFAULT false,
      "billing_day" integer,
      "next_billing_date" date,
      "renewal_date" date,
      "auto_renew" boolean NOT NULL DEFAULT false,
      "trial_ends_on" date,
      "cancellation_date" date,
      "status" text NOT NULL DEFAULT 'draft',
      "notes" text,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "vendor_bills" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "legal_entity_id" integer NOT NULL,
      "vendor_id" integer NOT NULL,
      "recurring_expense_id" integer,
      "invoice_number" text,
      "bill_kind" text NOT NULL DEFAULT 'invoice',
      "issue_date" date,
      "due_date" date,
      "service_period_start" date,
      "service_period_end" date,
      "amount_cents" integer NOT NULL,
      "currency" text NOT NULL DEFAULT 'USD',
      "category_code" text NOT NULL,
      "status" text NOT NULL DEFAULT 'draft',
      "credit_for_vendor_bill_id" integer,
      "notes" text,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "expense_payments" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "legal_entity_id" integer NOT NULL,
      "vendor_id" integer,
      "amount_cents" integer NOT NULL,
      "currency" text NOT NULL DEFAULT 'USD',
      "direction" text NOT NULL DEFAULT 'outflow',
      "payment_date" date,
      "method_type" text NOT NULL,
      "method_label" text,
      "institution_name" text,
      "masked_last4" text,
      "external_confirmation_ref" text,
      "status" text NOT NULL DEFAULT 'pending',
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "vendor_bill_applications" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "target_vendor_bill_id" integer NOT NULL,
      "expense_payment_id" integer,
      "credit_vendor_bill_id" integer,
      "amount_cents" integer NOT NULL,
      "currency" text NOT NULL DEFAULT 'USD',
      "status" text NOT NULL DEFAULT 'active',
      "reversed_at" timestamp,
      "reversed_by" integer,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE UNIQUE INDEX "idx_vendor_bill_payment_applications_active_unique"
      ON "vendor_bill_applications" ("target_vendor_bill_id", "expense_payment_id")
      WHERE "status" = 'active' AND "expense_payment_id" IS NOT NULL;

    CREATE UNIQUE INDEX "idx_vendor_bill_credit_applications_active_unique"
      ON "vendor_bill_applications" ("target_vendor_bill_id", "credit_vendor_bill_id")
      WHERE "status" = 'active' AND "credit_vendor_bill_id" IS NOT NULL;

    CREATE TABLE "finance_audit_events" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "actor_admin_user_id" integer NOT NULL,
      "entity_type" text NOT NULL,
      "entity_id" integer NOT NULL,
      "action" text NOT NULL,
      "changes_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
      "created_at" timestamp DEFAULT now()
    );

    CREATE TABLE "documents" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "storage_provider" text NOT NULL,
      "file_key" text NOT NULL,
      "file_sha256" text NOT NULL,
      "file_content_type" text NOT NULL,
      "file_size_bytes" integer NOT NULL,
      "original_filename" text,
      "document_type" text NOT NULL,
      "sensitivity_class" text NOT NULL,
      "status" text NOT NULL DEFAULT 'active',
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "document_links" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "document_id" integer NOT NULL,
      "entity_type" text NOT NULL,
      "entity_id" integer NOT NULL,
      "link_type" text NOT NULL,
      "required_sensitivity_class" text NOT NULL,
      "status" text NOT NULL DEFAULT 'active',
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "reconciliation_exceptions" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "domain" text NOT NULL,
      "expected_entity_type" text,
      "expected_entity_id" integer,
      "actual_entity_type" text,
      "actual_entity_id" integer,
      "currency" text,
      "expected_amount_cents" integer,
      "actual_amount_cents" integer,
      "difference_amount_cents" integer NOT NULL,
      "reason_code" text NOT NULL,
      "summary" text NOT NULL,
      "status" text NOT NULL DEFAULT 'open',
      "owner_admin_id" integer,
      "resolved_at" timestamp,
      "resolved_by" integer,
      "resolution_notes" text,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );
  `);
}

async function createPre0028RecurringExpensesTable(client: PoolClient) {
  await client.query(`
    CREATE TABLE "recurring_expenses" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "legal_entity_id" integer NOT NULL,
      "vendor_id" integer NOT NULL,
      "category_code" text NOT NULL,
      "cadence" text NOT NULL,
      "expected_amount_cents" integer,
      "currency" text NOT NULL DEFAULT 'USD',
      "variable_amount" boolean NOT NULL DEFAULT false,
      "billing_day" integer,
      "next_billing_date" date,
      "renewal_date" date,
      "auto_renew" boolean NOT NULL DEFAULT false,
      "trial_ends_on" date,
      "cancellation_date" date,
      "status" text NOT NULL DEFAULT 'draft',
      "notes" text,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );
  `);
}

async function withApSchema<T>(work: (client: PoolClient, schemaName: string) => Promise<T>) {
  assert.ok(POSTGRES_TEST_DATABASE_URL);
  assertDisposablePostgresTestUrl(POSTGRES_TEST_DATABASE_URL);
  const pool = createPostgresPool(POSTGRES_TEST_DATABASE_URL, {
    sslEnvNames: ["MIGRATION_RUNNER_TEST_DB_SSL", "DB_SSL"],
  });
  const client = await pool.connect();
  const schemaName = testSchemaName();

  try {
    await client.query(`CREATE SCHEMA "${schemaName}"`);
    await client.query(`SET search_path TO "${schemaName}", public`);
    await createApTables(client);
    await client.query(`
      INSERT INTO "legal_entities" ("id", "legal_name", "status")
      VALUES (1, 'Test LLC', 'active');
    `);
    return await work(client, schemaName);
  } finally {
    await client.query(`DROP SCHEMA IF EXISTS "${schemaName}" CASCADE`).catch(() => undefined);
    client.release();
    await pool.end();
  }
}

function repoForClient(client: PoolClient) {
  return createFinanceExpenseRepository(drizzle(client));
}

test(
  "0028 recurring expense name migration adds required nonblank identity on an empty table",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    assert.ok(POSTGRES_TEST_DATABASE_URL);
    assertDisposablePostgresTestUrl(POSTGRES_TEST_DATABASE_URL);
    const migration = readFileSync("migrations/0028_recurring_expense_name.sql", "utf8");
    assert.doesNotMatch(migration, /invoice_number/i);

    const pool = createPostgresPool(POSTGRES_TEST_DATABASE_URL, {
      sslEnvNames: ["MIGRATION_RUNNER_TEST_DB_SSL", "DB_SSL"],
    });
    const client = await pool.connect();
    const schemaName = testSchemaName();

    try {
      await client.query(`CREATE SCHEMA "${schemaName}"`);
      await client.query(`SET search_path TO "${schemaName}", public`);
      await createPre0028RecurringExpensesTable(client);
      await client.query(migration);

      const column = await client.query(
        `
          SELECT "is_nullable"
          FROM information_schema.columns
          WHERE "table_schema" = $1
            AND "table_name" = 'recurring_expenses'
            AND "column_name" = 'name'
        `,
        [schemaName],
      );
      assert.equal(column.rows[0].is_nullable, "NO");
      const invoiceColumn = await client.query(
        `
          SELECT 1
          FROM information_schema.columns
          WHERE "table_schema" = $1
            AND "table_name" = 'recurring_expenses'
            AND "column_name" = 'invoice_number'
        `,
        [schemaName],
      );
      assert.equal(invoiceColumn.rowCount, 0);

      const constraint = await client.query(
        `
          SELECT pg_get_constraintdef(c.oid) AS definition
          FROM pg_constraint c
          JOIN pg_class t ON t.oid = c.conrelid
          JOIN pg_namespace n ON n.oid = t.relnamespace
          WHERE n.nspname = $1
            AND t.relname = 'recurring_expenses'
            AND c.conname = 'recurring_expenses_name_check'
        `,
        [schemaName],
      );
      assert.match(constraint.rows[0].definition, /btrim\(name\) <> ''::text/);

      await assert.rejects(
        () => client.query(`
          INSERT INTO "recurring_expenses"
            ("legal_entity_id", "vendor_id", "name", "category_code", "cadence", "currency", "variable_amount", "status")
          VALUES (1, 20, '   ', 'domain', 'annual', 'USD', false, 'active')
        `),
        (error: unknown) => typeof error === "object" && error !== null && "code" in error && error.code === "23514",
      );

      await client.query(`
        INSERT INTO "recurring_expenses"
          ("legal_entity_id", "vendor_id", "name", "category_code", "cadence", "currency", "variable_amount", "status")
        VALUES (1, 20, 'ahhh-yaotu.com domain renewal', 'domain', 'annual', 'USD', false, 'active')
      `);
      const rows = await client.query(`SELECT "name", "category_code", "notes" FROM "recurring_expenses"`);
      assert.deepEqual(rows.rows, [{
        name: "ahhh-yaotu.com domain renewal",
        category_code: "domain",
        notes: null,
      }]);
    } finally {
      await client.query(`DROP SCHEMA IF EXISTS "${schemaName}" CASCADE`).catch(() => undefined);
      client.release();
      await pool.end();
    }
  },
);

test(
  "0028 recurring expense name migration refuses existing unnamed rows",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    assert.ok(POSTGRES_TEST_DATABASE_URL);
    assertDisposablePostgresTestUrl(POSTGRES_TEST_DATABASE_URL);
    const migration = readFileSync("migrations/0028_recurring_expense_name.sql", "utf8");
    const pool = createPostgresPool(POSTGRES_TEST_DATABASE_URL, {
      sslEnvNames: ["MIGRATION_RUNNER_TEST_DB_SSL", "DB_SSL"],
    });
    const client = await pool.connect();
    const schemaName = testSchemaName();

    try {
      await client.query(`CREATE SCHEMA "${schemaName}"`);
      await client.query(`SET search_path TO "${schemaName}", public`);
      await createPre0028RecurringExpensesTable(client);
      await client.query(`
        INSERT INTO "recurring_expenses"
          ("legal_entity_id", "vendor_id", "category_code", "cadence", "currency", "variable_amount", "status")
        VALUES (1, 20, 'domain', 'annual', 'USD', false, 'active')
      `);

      await assert.rejects(
        () => client.query(migration),
        /0028_recurring_expense_name requires explicit recurring expense names before migration/,
      );
    } finally {
      await client.query(`DROP SCHEMA IF EXISTS "${schemaName}" CASCADE`).catch(() => undefined);
      client.release();
      await pool.end();
    }
  },
);

test(
  "V2 AP repository preserves transaction rollback when audit insert fails on disposable PostgreSQL",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    await withApSchema(async (client) => {
      await client.query(`ALTER TABLE "finance_audit_events" ADD CONSTRAINT "reject_created_audit" CHECK ("action" <> 'created')`);
      const repo = repoForClient(client);

      await assert.rejects(
        () => createFinanceVendor(repo, {
          name: "Rollback Vendor",
          vendorType: "saas",
          status: "active",
          actorAdminId: 42,
        }),
        /violates check constraint/,
      );

      const vendors = await client.query(`SELECT "id" FROM "vendors" WHERE "name" = 'Rollback Vendor'`);
      assert.equal(vendors.rowCount, 0);
    });
  },
);

test(
  "V2 AP repository locks vendor bills with SELECT FOR UPDATE on the same transaction connection",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    assert.ok(POSTGRES_TEST_DATABASE_URL);
    assertDisposablePostgresTestUrl(POSTGRES_TEST_DATABASE_URL);
    const pool = createPostgresPool(POSTGRES_TEST_DATABASE_URL, {
      sslEnvNames: ["MIGRATION_RUNNER_TEST_DB_SSL", "DB_SSL"],
    });
    const clientA = await pool.connect();
    const clientB = await pool.connect();
    const schemaName = testSchemaName();
    let releaseTransaction!: () => void;
    const holdTransaction = new Promise<void>((resolve) => {
      releaseTransaction = resolve;
    });
    let locked!: () => void;
    const lockAcquired = new Promise<void>((resolve) => {
      locked = resolve;
    });

    try {
      await clientA.query(`CREATE SCHEMA "${schemaName}"`);
      await clientA.query(`SET search_path TO "${schemaName}", public`);
      await createApTables(clientA);
      await clientA.query(`INSERT INTO "legal_entities" ("id", "legal_name", "status") VALUES (1, 'Test LLC', 'active')`);
      await clientA.query(`INSERT INTO "vendors" ("id", "name", "vendor_type", "status") VALUES (20, 'Vendor A', 'saas', 'active')`);
      await clientA.query(`
        INSERT INTO "vendor_bills"
          ("id", "legal_entity_id", "vendor_id", "invoice_number", "bill_kind", "amount_cents", "currency", "category_code", "status")
        VALUES (10, 1, 20, 'INV-LOCK', 'invoice', 10000, 'USD', 'saas', 'approved')
      `);
      await clientB.query(`SET search_path TO "${schemaName}", public`);
      await clientB.query(`SET lock_timeout TO '100ms'`);

      const repo = repoForClient(clientA);
      const transaction = repo.transaction(async (tx) => {
        await tx.lockVendorBill(10);
        locked();
        await holdTransaction;
      });

      await lockAcquired;
      await assert.rejects(
        () => clientB.query(`UPDATE "vendor_bills" SET "notes" = 'blocked' WHERE "id" = 10`),
        (error: unknown) => typeof error === "object" && error !== null && "code" in error && error.code === "55P03",
      );

      releaseTransaction();
      await transaction;
    } finally {
      releaseTransaction();
      await clientA.query(`DROP SCHEMA IF EXISTS "${schemaName}" CASCADE`).catch(() => undefined);
      clientA.release();
      clientB.release();
      await pool.end();
    }
  },
);

test(
  "V2 AP bill-first record payment is atomic on disposable PostgreSQL",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    await withApSchema(async (client) => {
      const repo = repoForClient(client);
      await client.query(`INSERT INTO "vendors" ("id", "name", "vendor_type", "status") VALUES (20, 'Vendor A', 'saas', 'active')`);

      const fullBill = await createFinanceBill(repo, {
        legalEntityId: 1,
        vendorId: 20,
        invoiceNumber: "INV-FULL",
        billKind: "invoice",
        amountCents: 10_000,
        currency: "USD",
        categoryCode: "saas",
        status: "draft",
        actorAdminId: 42,
      });
      await transitionFinanceBillStatus(repo, fullBill.id, "receive", { actorAdminId: 42 });
      await transitionFinanceBillStatus(repo, fullBill.id, "approve", { actorAdminId: 42 });
      const full = await recordFinanceBillPayment(repo, fullBill.id, {
        amountCents: 10_000,
        direction: "outflow",
        paymentDate: "2026-08-29",
        methodType: "card",
        status: "cleared",
        actorAdminId: 42,
      });

      let bills = await listFinanceBills(repo, { pageSize: 100 });
      let payments = await listFinancePayments(repo, { pageSize: 100 });
      assert.equal(bills.find((bill) => bill.id === fullBill.id)?.remainingAmountCents, 0);
      assert.equal(payments.find((payment) => payment.id === full.payment.id)?.remainingAmountCents, 0);

      const partialBill = await createFinanceBill(repo, {
        legalEntityId: 1,
        vendorId: 20,
        invoiceNumber: "INV-PARTIAL",
        billKind: "invoice",
        amountCents: 10_000,
        currency: "USD",
        categoryCode: "saas",
        status: "draft",
        actorAdminId: 42,
      });
      await transitionFinanceBillStatus(repo, partialBill.id, "receive", { actorAdminId: 42 });
      await transitionFinanceBillStatus(repo, partialBill.id, "approve", { actorAdminId: 42 });
      await recordFinanceBillPayment(repo, partialBill.id, {
        amountCents: 4_000,
        direction: "outflow",
        paymentDate: "2026-08-30",
        methodType: "ach",
        status: "posted",
        actorAdminId: 42,
      });
      bills = await listFinanceBills(repo, { pageSize: 100 });
      assert.equal(bills.find((bill) => bill.id === partialBill.id)?.remainingAmountCents, 6_000);

      const paymentCountBeforeOverApply = await client.query(`SELECT count(*)::int AS "count" FROM "expense_payments"`);
      await assert.rejects(
        () => recordFinanceBillPayment(repo, partialBill.id, {
          amountCents: 6_001,
          direction: "outflow",
          paymentDate: "2026-08-31",
          methodType: "card",
          status: "cleared",
          actorAdminId: 42,
        }),
        (error) => error instanceof FinanceExpenseServiceError && error.code === "AP_BILL_OVER_APPLIED",
      );
      const paymentCountAfterOverApply = await client.query(`SELECT count(*)::int AS "count" FROM "expense_payments"`);
      assert.equal(paymentCountAfterOverApply.rows[0].count, paymentCountBeforeOverApply.rows[0].count);

      const auditCountBeforeRollback = await client.query(`SELECT count(*)::int AS "count" FROM "finance_audit_events"`);
      await client.query(`ALTER TABLE "vendor_bill_applications" ADD CONSTRAINT "reject_bill_first_application" CHECK ("amount_cents" < 0) NOT VALID`);
      const rollbackBill = await createFinanceBill(repo, {
        legalEntityId: 1,
        vendorId: 20,
        invoiceNumber: "INV-ROLLBACK",
        billKind: "invoice",
        amountCents: 2_000,
        currency: "USD",
        categoryCode: "saas",
        status: "draft",
        actorAdminId: 42,
      });
      await transitionFinanceBillStatus(repo, rollbackBill.id, "receive", { actorAdminId: 42 });
      await transitionFinanceBillStatus(repo, rollbackBill.id, "approve", { actorAdminId: 42 });
      const auditCountAfterBillSetup = await client.query(`SELECT count(*)::int AS "count" FROM "finance_audit_events"`);
      await assert.rejects(
        () => recordFinanceBillPayment(repo, rollbackBill.id, {
          amountCents: 2_000,
          direction: "outflow",
          paymentDate: "2026-09-01",
          methodType: "card",
          methodLabel: "rollback-marker",
          status: "cleared",
          actorAdminId: 42,
        }),
        /violates check constraint/,
      );
      const rolledBackPayments = await client.query(`SELECT "id" FROM "expense_payments" WHERE "method_label" = 'rollback-marker'`);
      const rolledBackApplications = await client.query(`SELECT "id" FROM "vendor_bill_applications" WHERE "target_vendor_bill_id" = $1`, [rollbackBill.id]);
      const auditCountAfterRollback = await client.query(`SELECT count(*)::int AS "count" FROM "finance_audit_events"`);
      assert.equal(rolledBackPayments.rowCount, 0);
      assert.equal(rolledBackApplications.rowCount, 0);
      assert.equal(auditCountAfterRollback.rows[0].count, auditCountAfterBillSetup.rows[0].count);
      assert.ok(auditCountAfterBillSetup.rows[0].count > auditCountBeforeRollback.rows[0].count);
    });
  },
);

test(
  "V2 AP already-paid bill intake creates approved paid bill atomically on disposable PostgreSQL",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    await withApSchema(async (client) => {
      const repo = repoForClient(client);
      await client.query(`INSERT INTO "vendors" ("id", "name", "vendor_type", "status") VALUES (20, 'Vendor A', 'saas', 'active')`);

      const result = await recordPaidFinanceBill(repo, {
        legalEntityId: 1,
        vendorId: 20,
        invoiceNumber: "IN-ALREADY-PAID",
        billKind: "invoice",
        issueDate: "2026-08-29",
        dueDate: "2026-08-29",
        amountCents: 1_046,
        currency: "USD",
        categoryCode: "saas",
        paymentDate: "2026-08-29",
        methodType: "card",
        methodLabel: "Apple Card",
        maskedLast4: "3231",
        actorAdminId: 42,
      });

      assert.equal(result.bill.status, "approved");
      assert.equal(result.payment.status, "cleared");
      assert.equal(result.payment.direction, "outflow");
      assert.equal(result.application.targetVendorBillId, result.bill.id);
      assert.equal(result.application.expensePaymentId, result.payment.id);
      assert.equal(result.application.amountCents, 1_046);

      const bills = await listFinanceBills(repo, { pageSize: 100 });
      const payments = await listFinancePayments(repo, { pageSize: 100 });
      assert.equal(bills.find((bill) => bill.id === result.bill.id)?.status, "approved");
      assert.equal(bills.find((bill) => bill.id === result.bill.id)?.settlementState, "paid");
      assert.equal(bills.find((bill) => bill.id === result.bill.id)?.remainingAmountCents, 0);
      assert.equal(payments.find((payment) => payment.id === result.payment.id)?.status, "cleared");
      assert.equal(payments.find((payment) => payment.id === result.payment.id)?.remainingAmountCents, 0);

      const applicationRows = await client.query(
        `
          SELECT "target_vendor_bill_id", "expense_payment_id", "amount_cents", "currency", "status"
          FROM "vendor_bill_applications"
          WHERE "target_vendor_bill_id" = $1
        `,
        [result.bill.id],
      );
      assert.deepEqual(applicationRows.rows, [{
        target_vendor_bill_id: result.bill.id,
        expense_payment_id: result.payment.id,
        amount_cents: 1_046,
        currency: "USD",
        status: "active",
      }]);

      const receivedBill = await createFinanceBill(repo, {
        legalEntityId: 1,
        vendorId: 20,
        invoiceNumber: "IN-APPROVE-AND-PAY",
        billKind: "invoice",
        amountCents: 2_000,
        currency: "USD",
        categoryCode: "saas",
        status: "draft",
        actorAdminId: 42,
      });
      await transitionFinanceBillStatus(repo, receivedBill.id, "receive", { actorAdminId: 42 });
      const approvedPayment = await approveAndRecordFinanceBillPayment(repo, receivedBill.id, {
        amountCents: 2_000,
        direction: "outflow",
        paymentDate: "2026-08-30",
        methodType: "card",
        status: "cleared",
        actorAdminId: 42,
      });
      assert.equal(approvedPayment.bill.status, "approved");
      const updatedBills = await listFinanceBills(repo, { pageSize: 100 });
      assert.equal(updatedBills.find((bill) => bill.id === receivedBill.id)?.settlementState, "paid");
      assert.equal(updatedBills.find((bill) => bill.id === receivedBill.id)?.remainingAmountCents, 0);

      const auditEvents = await client.query<{ entity_type: string; action: string }>(
        `SELECT "entity_type", "action" FROM "finance_audit_events" ORDER BY "id"`,
      );
      assert.deepEqual(
        auditEvents.rows.map((row) => `${row.entity_type}:${row.action}`),
        [
          "vendor_bill:created",
          "vendor_bill:received",
          "vendor_bill:approved",
          "expense_payment:created",
          "vendor_bill_application:applied",
          "vendor_bill:created",
          "vendor_bill:received",
          "vendor_bill:approved",
          "expense_payment:created",
          "vendor_bill_application:applied",
        ],
      );
    });
  },
);

test(
  "V2 AP overview spend uses cleared outflow payments once on disposable PostgreSQL",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    await withApSchema(async (client) => {
      const repo = repoForClient(client);
      await client.query(`INSERT INTO "vendors" ("id", "name", "vendor_type", "status") VALUES (20, 'Cloudflare', 'cloud', 'active')`);
      await client.query(`
        INSERT INTO "vendor_bills"
          ("id", "legal_entity_id", "vendor_id", "invoice_number", "bill_kind", "due_date", "amount_cents", "currency", "category_code", "status")
        VALUES
          (100, 1, 20, 'IN-A', 'invoice', '2026-09-10', 1000, 'USD', 'cloud', 'approved'),
          (101, 1, 20, 'IN-B', 'invoice', '2026-09-11', 1000, 'USD', 'cloud', 'approved')
      `);
      await client.query(`
        INSERT INTO "expense_payments"
          ("id", "legal_entity_id", "vendor_id", "amount_cents", "currency", "direction", "payment_date", "method_type", "status")
        VALUES
          (200, 1, 20, 1000, 'USD', 'outflow', '2026-09-02', 'card', 'cleared'),
          (201, 1, 20, 2000, 'USD', 'outflow', '2026-01-15', 'card', 'cleared'),
          (202, 1, 20, 3000, 'USD', 'refund', '2026-09-03', 'card', 'cleared'),
          (203, 1, 20, 4000, 'USD', 'outflow', '2026-09-03', 'card', 'pending'),
          (204, 1, 20, 5000, 'USD', 'outflow', '2026-09-03', 'card', 'failed'),
          (205, 1, 20, 6000, 'USD', 'outflow', '2026-09-03', 'card', 'voided'),
          (206, 1, 20, 7000, 'USD', 'outflow', '2026-09-03', 'card', 'reversed'),
          (207, 1, 20, 8000, 'USD', 'outflow', '2025-12-31', 'card', 'cleared'),
          (208, 1, 20, 9000, 'USD', 'outflow', '2026-10-01', 'card', 'cleared')
      `);
      await client.query(`
        INSERT INTO "vendor_bill_applications"
          ("target_vendor_bill_id", "expense_payment_id", "amount_cents", "currency", "status")
        VALUES
          (100, 200, 400, 'USD', 'active'),
          (101, 200, 600, 'USD', 'active')
      `);

      const overview = await getFinanceOverview(repo, "2026-09-04");

      assert.deepEqual(overview.metrics.paidThisMonthByCurrency, [
        { currency: "USD", amountCents: 1000 },
      ]);
      assert.deepEqual(overview.metrics.paidYtdByCurrency, [
        { currency: "USD", amountCents: 3000 },
      ]);
    });
  },
);

test(
  "V2 AP payment ledger saved views filter completed outflow rows for drill-down subtotals",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    await withApSchema(async (client) => {
      const repo = repoForClient(client);
      await client.query(`INSERT INTO "vendors" ("id", "name", "vendor_type", "status") VALUES (20, 'Cloudflare', 'cloud', 'active')`);
      await client.query(`
        INSERT INTO "vendor_bills"
          ("id", "legal_entity_id", "vendor_id", "invoice_number", "bill_kind", "due_date", "amount_cents", "currency", "category_code", "status")
        VALUES
          (100, 1, 20, 'IN-A', 'invoice', '2026-09-10', 1000, 'USD', 'cloud', 'approved'),
          (101, 1, 20, 'IN-B', 'invoice', '2026-09-11', 1000, 'USD', 'cloud', 'approved')
      `);
      await client.query(`
        INSERT INTO "expense_payments"
          ("id", "legal_entity_id", "vendor_id", "amount_cents", "currency", "direction", "payment_date", "method_type", "status")
        VALUES
          (200, 1, 20, 1000, 'USD', 'outflow', '2026-09-02', 'card', 'cleared'),
          (201, 1, 20, 2000, 'USD', 'outflow', '2026-01-15', 'card', 'cleared'),
          (202, 1, 20, 3000, 'USD', 'refund', '2026-09-03', 'card', 'cleared'),
          (203, 1, 20, 4000, 'USD', 'outflow', '2026-09-03', 'card', 'pending'),
          (204, 1, 20, 5000, 'USD', 'outflow', '2026-09-03', 'card', 'failed'),
          (205, 1, 20, 6000, 'USD', 'outflow', '2026-09-03', 'card', 'voided'),
          (206, 1, 20, 7000, 'USD', 'outflow', '2026-09-03', 'card', 'reversed'),
          (207, 1, 20, 8000, 'USD', 'outflow', '2025-12-31', 'card', 'cleared')
      `);
      await client.query(`
        INSERT INTO "vendor_bill_applications"
          ("target_vendor_bill_id", "expense_payment_id", "amount_cents", "currency", "status")
        VALUES
          (100, 200, 400, 'USD', 'active'),
          (101, 200, 600, 'USD', 'active')
      `);

      const ytdLedger = await listFinancePaymentLedger(repo, {
        pageSize: 1,
        period: "custom",
        scope: "completed-outflow",
        paymentFrom: "2026-01-01",
        paymentTo: "2026-09-04",
      });
      assert.deepEqual(ytdLedger.payments.map((payment) => payment.id), [200]);
      assert.equal(ytdLedger.summary.count, 2);
      assert.deepEqual(ytdLedger.summary.totalAmountByCurrency, [{ currency: "USD", amountCents: 3000 }]);
      assert.deepEqual(ytdLedger.summary.appliedAmountByCurrency, [{ currency: "USD", amountCents: 1000 }]);
      assert.deepEqual(ytdLedger.summary.unappliedAmountByCurrency, [{ currency: "USD", amountCents: 2000 }]);

      const monthLedger = await listFinancePaymentLedger(repo, {
        pageSize: 100,
        period: "custom",
        scope: "completed-outflow",
        paymentFrom: "2026-09-01",
        paymentTo: "2026-09-30",
      });
      assert.deepEqual(monthLedger.payments.map((payment) => payment.id), [200]);
      assert.deepEqual(monthLedger.summary.totalAmountByCurrency, [{ currency: "USD", amountCents: 1000 }]);
      assert.deepEqual(monthLedger.summary.appliedAmountByCurrency, [{ currency: "USD", amountCents: 1000 }]);
      assert.deepEqual(monthLedger.summary.unappliedAmountByCurrency, [{ currency: "USD", amountCents: 0 }]);
    });
  },
);

test(
  "V2 AP payment ledger dates follow paymentDate for historical bookkeeping",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    await withApSchema(async (client) => {
      const repo = repoForClient(client);
      await client.query(`INSERT INTO "vendors" ("id", "name", "vendor_type", "status") VALUES (20, 'Cloudflare', 'cloud', 'active')`);
      await client.query(`
        INSERT INTO "vendor_bills"
          ("id", "legal_entity_id", "vendor_id", "invoice_number", "bill_kind", "due_date", "amount_cents", "currency", "category_code", "status")
        VALUES
          (100, 1, 20, 'IN-48888602', 'invoice', '2025-09-28', 1046, 'USD', 'domain', 'approved'),
          (101, 1, 20, 'IN-77096614', 'invoice', '2026-08-29', 1046, 'USD', 'domain', 'approved')
      `);
      await client.query(`
        INSERT INTO "expense_payments"
          ("id", "legal_entity_id", "vendor_id", "amount_cents", "currency", "direction", "payment_date", "method_type", "method_label", "status", "created_at")
        VALUES
          (200, 1, 20, 1046, 'USD', 'outflow', '2025-09-28', 'other', 'PayPal', 'cleared', '2026-09-04'),
          (201, 1, 20, 1046, 'USD', 'outflow', '2026-08-29', 'card', 'Apple Card', 'cleared', '2026-09-04')
      `);
      await client.query(`
        INSERT INTO "vendor_bill_applications"
          ("target_vendor_bill_id", "expense_payment_id", "amount_cents", "currency", "status")
        VALUES
          (100, 200, 1046, 'USD', 'active'),
          (101, 201, 1046, 'USD', 'active')
      `);

      const overview = await getFinanceOverview(repo, "2026-09-04");
      assert.deepEqual(overview.metrics.paidThisMonthByCurrency, []);
      assert.deepEqual(overview.metrics.paidYtdByCurrency, [
        { currency: "USD", amountCents: 1046 },
      ]);

      const thisMonthLedger = await listFinancePaymentLedger(repo, {
        pageSize: 100,
        period: "custom",
        scope: "completed-outflow",
        paymentFrom: "2026-09-01",
        paymentTo: "2026-09-04",
      });
      assert.equal(thisMonthLedger.summary.count, 0);
      assert.deepEqual(thisMonthLedger.summary.totalAmountByCurrency, []);

      const ytdLedger = await listFinancePaymentLedger(repo, {
        pageSize: 100,
        period: "custom",
        scope: "completed-outflow",
        paymentFrom: "2026-01-01",
        paymentTo: "2026-09-04",
      });
      assert.equal(ytdLedger.summary.count, 1);
      assert.deepEqual(ytdLedger.summary.totalAmountByCurrency, [
        { currency: "USD", amountCents: 1046 },
      ]);

      const allTimeLedger = await listFinancePaymentLedger(repo, {
        pageSize: 100,
        period: "all-time",
        scope: "completed-outflow",
      });
      assert.equal(allTimeLedger.summary.count, 2);
      assert.deepEqual(allTimeLedger.summary.totalAmountByCurrency, [
        { currency: "USD", amountCents: 2092 },
      ]);
      assert.deepEqual(allTimeLedger.summary.appliedAmountByCurrency, [
        { currency: "USD", amountCents: 2092 },
      ]);
      assert.deepEqual(allTimeLedger.summary.unappliedAmountByCurrency, [
        { currency: "USD", amountCents: 0 },
      ]);
    });
  },
);

test(
  "V2 AP already-paid bill intake rolls back bill, payment, application, and audit rows on disposable PostgreSQL",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    const cases = [
      {
        label: "payment",
        invoiceNumber: "IN-PAYMENT-ROLLBACK",
        methodLabel: "payment-rollback-marker",
        setup: async (client: PoolClient) => {
          await client.query(`ALTER TABLE "expense_payments" ADD CONSTRAINT "reject_payment_marker" CHECK ("method_label" <> 'payment-rollback-marker')`);
        },
        expected: /violates check constraint/,
      },
      {
        label: "application",
        invoiceNumber: "IN-APPLICATION-ROLLBACK",
        methodLabel: "application-rollback-marker",
        setup: async (client: PoolClient) => {
          await client.query(`ALTER TABLE "vendor_bill_applications" ADD CONSTRAINT "reject_already_paid_application" CHECK ("amount_cents" < 0) NOT VALID`);
        },
        expected: /violates check constraint/,
      },
      {
        label: "audit",
        invoiceNumber: "IN-AUDIT-ROLLBACK",
        methodLabel: "audit-rollback-marker",
        setup: async (client: PoolClient) => {
          await client.query(`ALTER TABLE "finance_audit_events" ADD CONSTRAINT "reject_created_audit" CHECK ("action" <> 'created')`);
        },
        expected: /violates check constraint/,
      },
    ];

    for (const failureCase of cases) {
      await withApSchema(async (client) => {
        const repo = repoForClient(client);
        await client.query(`INSERT INTO "vendors" ("id", "name", "vendor_type", "status") VALUES (20, 'Vendor A', 'saas', 'active')`);
        await failureCase.setup(client);

        await assert.rejects(
          () => recordPaidFinanceBill(repo, {
            legalEntityId: 1,
            vendorId: 20,
            invoiceNumber: failureCase.invoiceNumber,
            billKind: "invoice",
            amountCents: 1_046,
            currency: "USD",
            categoryCode: "saas",
            paymentDate: "2026-08-29",
            methodType: "card",
            methodLabel: failureCase.methodLabel,
            actorAdminId: 42,
          }),
          failureCase.expected,
        );

        const billRows = await client.query(`SELECT "id" FROM "vendor_bills" WHERE "invoice_number" = $1`, [failureCase.invoiceNumber]);
        const paymentRows = await client.query(`SELECT "id" FROM "expense_payments" WHERE "method_label" = $1`, [failureCase.methodLabel]);
        const applicationRows = await client.query(`SELECT "id" FROM "vendor_bill_applications"`);
        const auditRows = await client.query(`SELECT "id" FROM "finance_audit_events"`);
        assert.equal(billRows.rowCount, 0, `${failureCase.label} failure left a bill row`);
        assert.equal(paymentRows.rowCount, 0, `${failureCase.label} failure left a payment row`);
        assert.equal(applicationRows.rowCount, 0, `${failureCase.label} failure left an application row`);
        assert.equal(auditRows.rowCount, 0, `${failureCase.label} failure left an audit row`);
      });
    }
  },
);

test(
  "V2 AP disposable PostgreSQL path preserves bill lifecycle, payment application, reconciliation, and audit rows",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    await withApSchema(async (client) => {
      const repo = repoForClient(client);
      await client.query(`INSERT INTO "vendors" ("id", "name", "vendor_type", "status") VALUES (20, 'Vendor A', 'saas', 'active')`);

      const bill = await createFinanceBill(repo, {
        legalEntityId: 1,
        vendorId: 20,
        invoiceNumber: "INV-100",
        billKind: "invoice",
        amountCents: 10_000,
        currency: "USD",
        categoryCode: "saas",
        status: "draft",
        actorAdminId: 42,
      });
      assert.equal(financeBillResponse(bill).status, "draft");

      await assert.rejects(
        () => createFinanceBill(repo, {
          legalEntityId: 1,
          vendorId: 20,
          invoiceNumber: "INV-100",
          billKind: "invoice",
          amountCents: 10_000,
          currency: "USD",
          categoryCode: "saas",
          status: "draft",
          actorAdminId: 42,
        }),
        (error) => error instanceof FinanceExpenseServiceError && error.code === "VENDOR_BILL_INVOICE_DUPLICATE",
      );

      await transitionFinanceBillStatus(repo, bill.id, "receive", { actorAdminId: 42 });
      await transitionFinanceBillStatus(repo, bill.id, "approve", { actorAdminId: 42 });
      await assert.rejects(
        () => transitionFinanceBillStatus(repo, bill.id, "receive", { actorAdminId: 42 }),
        (error) => error instanceof FinanceExpenseServiceError && error.code === "BILL_RECEIVE_REQUIRES_DRAFT",
      );

      const payment = await recordFinancePayment(repo, {
        legalEntityId: 1,
        vendorId: 20,
        amountCents: 10_000,
        currency: "USD",
        direction: "outflow",
        methodType: "ach",
        status: "cleared",
        actorAdminId: 42,
      });
      await applyFinancePaymentToBill(repo, {
        targetVendorBillId: bill.id,
        expensePaymentId: payment.id,
        amountCents: 6_000,
        currency: "USD",
        actorAdminId: 42,
      });

      const bills = await listFinanceBills(repo, { pageSize: 100 });
      const payments = await listFinancePayments(repo, { pageSize: 100 });
      assert.equal(bills[0].remainingAmountCents, 4_000);
      assert.equal(payments[0].remainingAmountCents, 4_000);

      await assert.rejects(
        () => applyFinancePaymentToBill(repo, {
          targetVendorBillId: bill.id,
          expensePaymentId: payment.id,
          amountCents: 1_000,
          currency: "USD",
          actorAdminId: 42,
        }),
        /duplicate key value violates unique constraint/,
      );

      const applicationCount = await client.query(`SELECT count(*)::int AS "count" FROM "vendor_bill_applications"`);
      assert.equal(applicationCount.rows[0].count, 1);

      const exception = await createFinanceReconciliationException(repo, {
        expectedEntityType: "vendor_bills",
        expectedEntityId: bill.id,
        actualEntityType: "expense_payments",
        actualEntityId: payment.id,
        expectedAmountCents: 10_000,
        actualAmountCents: 6_000,
        currency: "USD",
        reasonCode: "amount_mismatch",
        summary: "Partial application",
        actorAdminId: 42,
      });
      assert.equal(exception.status, "open");
      const investigated = await transitionFinanceReconciliationException(repo, exception.id, "investigate", { actorAdminId: 42 });
      assert.equal(investigated.status, "investigating");

      const auditEvents = await client.query<{ entity_type: string; action: string }>(
        `SELECT "entity_type", "action" FROM "finance_audit_events" ORDER BY "id"`,
      );
      assert.deepEqual(
        auditEvents.rows.map((row) => `${row.entity_type}:${row.action}`),
        [
          "vendor_bill:created",
          "vendor_bill:received",
          "vendor_bill:approved",
          "expense_payment:created",
          "vendor_bill_application:applied",
          "reconciliation_exception:created",
          "reconciliation_exception:investigating",
        ],
      );
    });
  },
);
