import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { drizzle } from "drizzle-orm/node-postgres";
import type { PoolClient } from "pg";

import { createPostgresPool } from "../../db-client";
import {
  applyTaxPaymentAllocation,
  createTaxAgency,
  createTaxExternalRecordRef,
  createTaxFiling,
  createTaxFilingAmendment,
  createTaxLiability,
  createTaxLiabilityAdjustment,
  createTaxReconciliationException,
  createTaxRegistration,
  recordTaxAgencyPayment,
  reverseTaxAgencyPayment,
  reverseTaxPaymentAllocation,
  TaxServiceError,
  transitionTaxFiling,
  transitionTaxLiability,
  transitionTaxReconciliationException,
} from "../../taxService";
import { createTaxRepository } from "../../taxRepositoryFactory";

const POSTGRES_TEST_DATABASE_URL = process.env.MIGRATION_RUNNER_TEST_DATABASE_URL;

function assertDisposablePostgresTestUrl(connectionString: string) {
  let databaseName = "";
  try {
    const parsed = new URL(connectionString.replace(/^postgres:\/\//, "postgresql://"));
    databaseName = decodeURIComponent(parsed.pathname.replace(/^\//, ""));
  } catch {
    throw new Error("MIGRATION_RUNNER_TEST_DATABASE_URL must be a valid PostgreSQL URL.");
  }

  if (!/(test|tmp|scratch|disposable|codex)/i.test(databaseName)) {
    throw new Error(
      "MIGRATION_RUNNER_TEST_DATABASE_URL must point to a disposable database whose name contains test, tmp, scratch, disposable, or codex.",
    );
  }
}

function testSchemaName() {
  return `stage9_tax_${process.pid}_${randomUUID().replace(/-/g, "").slice(0, 12)}`;
}

async function createTaxTables(client: PoolClient) {
  await client.query(`
    CREATE TABLE "admin_users" (
      "id" integer PRIMARY KEY,
      "email" text NOT NULL
    );

    CREATE TABLE "legal_entities" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "legal_name" text NOT NULL,
      "entity_type" text NOT NULL DEFAULT 'llc',
      "formation_state" text,
      "masked_tax_identifier" text,
      "status" text NOT NULL DEFAULT 'active',
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "vendors" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "name" text NOT NULL,
      "vendor_type" text NOT NULL DEFAULT 'other',
      "status" text NOT NULL DEFAULT 'active',
      "website" text,
      "contact_email" text,
      "notes" text,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "tax_agencies" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "agency_code" text NOT NULL,
      "name" text NOT NULL,
      "jurisdiction_type" text NOT NULL,
      "jurisdiction_code" text NOT NULL,
      "status" text NOT NULL DEFAULT 'active',
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );
    CREATE UNIQUE INDEX "idx_tax_agencies_code_unique" ON "tax_agencies" ("agency_code");

    CREATE TABLE "tax_registrations" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "legal_entity_id" integer NOT NULL,
      "tax_agency_id" integer NOT NULL,
      "tax_type" text NOT NULL,
      "jurisdiction_type" text NOT NULL,
      "jurisdiction_code" text NOT NULL,
      "masked_account_ref" text,
      "effective_from" date,
      "effective_to" date,
      "status" text NOT NULL DEFAULT 'pending',
      "notes" text,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "tax_liabilities" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "tax_registration_id" integer NOT NULL,
      "period_start" date NOT NULL,
      "period_end" date NOT NULL,
      "due_date" date,
      "component" text NOT NULL,
      "amount_effect" text NOT NULL DEFAULT 'increase',
      "amount_cents" integer NOT NULL,
      "currency" text NOT NULL DEFAULT 'USD',
      "source_type" text NOT NULL DEFAULT 'manual',
      "source_metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
      "adjusts_tax_liability_id" integer,
      "status" text NOT NULL DEFAULT 'draft',
      "recognized_at" timestamp,
      "notes" text,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "tax_agency_payments" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "tax_registration_id" integer NOT NULL,
      "amount_cents" integer NOT NULL,
      "currency" text NOT NULL DEFAULT 'USD',
      "payment_date" date,
      "method_type" text NOT NULL,
      "method_label" text,
      "institution_name" text,
      "masked_last4" text,
      "confirmation_ref" text,
      "status" text NOT NULL DEFAULT 'pending',
      "submitted_at" timestamp,
      "cleared_at" timestamp,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "tax_payment_allocations" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "tax_liability_id" integer NOT NULL,
      "tax_agency_payment_id" integer NOT NULL,
      "amount_cents" integer NOT NULL,
      "currency" text NOT NULL DEFAULT 'USD',
      "status" text NOT NULL DEFAULT 'active',
      "reversed_at" timestamp,
      "reversed_by" integer,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );
    CREATE UNIQUE INDEX "idx_tax_payment_allocations_active_unique"
      ON "tax_payment_allocations" ("tax_liability_id", "tax_agency_payment_id")
      WHERE "status" = 'active';

    CREATE TABLE "tax_filings" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "tax_registration_id" integer NOT NULL,
      "filing_type" text NOT NULL,
      "period_start" date NOT NULL,
      "period_end" date NOT NULL,
      "due_date" date,
      "filed_at" timestamp,
      "accepted_at" timestamp,
      "confirmation_ref" text,
      "amends_tax_filing_id" integer,
      "status" text NOT NULL DEFAULT 'draft',
      "notes" text,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );
    CREATE UNIQUE INDEX "idx_tax_filings_original_unique"
      ON "tax_filings" ("tax_registration_id", "filing_type", "period_start", "period_end")
      WHERE "amends_tax_filing_id" IS NULL AND "status" <> 'voided';

    CREATE TABLE "tax_audit_events" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "actor_admin_user_id" integer NOT NULL,
      "entity_type" text NOT NULL,
      "entity_id" integer NOT NULL,
      "action" text NOT NULL,
      "changes_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
      "created_at" timestamp DEFAULT now()
    );

    CREATE TABLE "external_record_refs" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "entity_type" text NOT NULL,
      "entity_id" integer NOT NULL,
      "source_type" text NOT NULL,
      "source_vendor_id" integer,
      "source_namespace" text NOT NULL DEFAULT 'default',
      "external_record_type" text NOT NULL,
      "external_record_id" text NOT NULL,
      "imported_at" timestamp,
      "payload_hash" text,
      "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
      "status" text NOT NULL DEFAULT 'active',
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "reconciliation_exceptions" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "domain" text NOT NULL,
      "expected_entity_type" text,
      "expected_entity_id" integer,
      "actual_entity_type" text,
      "actual_entity_id" integer,
      "currency" text,
      "expected_amount_cents" integer,
      "actual_amount_cents" integer,
      "difference_amount_cents" integer,
      "reason_code" text NOT NULL,
      "summary" text NOT NULL,
      "status" text NOT NULL DEFAULT 'open',
      "owner_admin_id" integer,
      "resolved_at" timestamp,
      "resolved_by" integer,
      "resolution_notes" text,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "payroll_runs" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    );

    CREATE TABLE "vendor_bills" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    );
  `);
}

async function seedTaxReferences(client: PoolClient) {
  await client.query(`
    INSERT INTO "admin_users" ("id", "email")
    VALUES (42, 'tax-admin@example.com');

    INSERT INTO "legal_entities" ("id", "legal_name", "entity_type", "masked_tax_identifier", "status")
    VALUES (1, 'Test LLC', 'llc', '***-**-1234', 'active');

    INSERT INTO "vendors" ("id", "name", "vendor_type", "status", "contact_email", "notes")
    VALUES (20, 'Provider', 'payroll_provider', 'active', 'private-vendor@example.com', 'private vendor note');
  `);
}

async function withTaxSchema<T>(
  work: (client: PoolClient, schemaName: string) => Promise<T>,
) {
  assert.ok(POSTGRES_TEST_DATABASE_URL);
  assertDisposablePostgresTestUrl(POSTGRES_TEST_DATABASE_URL);
  const pool = createPostgresPool(POSTGRES_TEST_DATABASE_URL, {
    sslEnvNames: ["MIGRATION_RUNNER_TEST_DB_SSL", "DB_SSL"],
  });
  const client = await pool.connect();
  const schemaName = testSchemaName();

  try {
    await client.query(`CREATE SCHEMA "${schemaName}"`);
    await client.query(`SET search_path TO "${schemaName}", public`);
    await createTaxTables(client);
    await seedTaxReferences(client);
    return await work(client, schemaName);
  } finally {
    await client.query(`DROP SCHEMA IF EXISTS "${schemaName}" CASCADE`).catch(() => undefined);
    client.release();
    await pool.end();
  }
}

function repoForClient(client: PoolClient) {
  return createTaxRepository(drizzle(client));
}

test(
  "V2 Tax repository preserves transaction rollback when audit insert fails on disposable PostgreSQL",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    await withTaxSchema(async (client) => {
      await client.query(`ALTER TABLE "tax_audit_events" ADD CONSTRAINT "reject_created_audit" CHECK ("action" <> 'created')`);
      const repo = repoForClient(client);

      await assert.rejects(
        () => createTaxAgency(repo, {
          agencyCode: "IRS-ROLLBACK",
          name: "Rollback Agency",
          jurisdictionType: "federal",
          jurisdictionCode: "US",
          status: "active",
          actorAdminId: 42,
        }),
        /violates check constraint/,
      );

      const agencies = await client.query(`SELECT "id" FROM "tax_agencies" WHERE "agency_code" = 'IRS-ROLLBACK'`);
      const auditEvents = await client.query(`SELECT "id" FROM "tax_audit_events"`);
      assert.equal(agencies.rowCount, 0);
      assert.equal(auditEvents.rowCount, 0);
    });
  },
);

test(
  "V2 Tax repository locks Tax liabilities with SELECT FOR UPDATE on the same transaction connection",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    assert.ok(POSTGRES_TEST_DATABASE_URL);
    assertDisposablePostgresTestUrl(POSTGRES_TEST_DATABASE_URL);
    const pool = createPostgresPool(POSTGRES_TEST_DATABASE_URL, {
      sslEnvNames: ["MIGRATION_RUNNER_TEST_DB_SSL", "DB_SSL"],
    });
    const clientA = await pool.connect();
    const clientB = await pool.connect();
    const schemaName = testSchemaName();
    let releaseTransaction!: () => void;
    const holdTransaction = new Promise<void>((resolve) => {
      releaseTransaction = resolve;
    });
    let locked!: () => void;
    const lockAcquired = new Promise<void>((resolve) => {
      locked = resolve;
    });

    try {
      await clientA.query(`CREATE SCHEMA "${schemaName}"`);
      await clientA.query(`SET search_path TO "${schemaName}", public`);
      await createTaxTables(clientA);
      await seedTaxReferences(clientA);
      await clientA.query(`
        INSERT INTO "tax_agencies" ("id", "agency_code", "name", "jurisdiction_type", "jurisdiction_code")
        VALUES (10, 'IRS', 'Internal Revenue Service', 'federal', 'US');

        INSERT INTO "tax_registrations"
          ("id", "legal_entity_id", "tax_agency_id", "tax_type", "jurisdiction_type", "jurisdiction_code", "status")
        VALUES (11, 1, 10, 'federal_withholding', 'federal', 'US', 'active');

        INSERT INTO "tax_liabilities"
          ("id", "tax_registration_id", "period_start", "period_end", "component", "amount_cents", "currency", "status")
        VALUES (12, 11, '2026-04-01', '2026-06-30', 'withholding', 10000, 'USD', 'recognized');
      `);
      await clientB.query(`SET search_path TO "${schemaName}", public`);
      await clientB.query(`SET lock_timeout TO '100ms'`);

      const repo = repoForClient(clientA);
      const transaction = repo.transaction(async (tx) => {
        await tx.lockTaxLiability(12);
        locked();
        await holdTransaction;
      });

      await lockAcquired;
      await assert.rejects(
        () => clientB.query(`UPDATE "tax_liabilities" SET "notes" = 'blocked' WHERE "id" = 12`),
        (error: unknown) => typeof error === "object" && error !== null && "code" in error && error.code === "55P03",
      );

      releaseTransaction();
      await transaction;
    } finally {
      releaseTransaction();
      await clientA.query(`DROP SCHEMA IF EXISTS "${schemaName}" CASCADE`).catch(() => undefined);
      clientA.release();
      clientB.release();
      await pool.end();
    }
  },
);

test(
  "V2 Tax disposable PostgreSQL path preserves ledger lifecycle, allocation atomicity, audit, and AP/Payroll isolation",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    await withTaxSchema(async (client) => {
      const repo = repoForClient(client);

      const agency = await createTaxAgency(repo, {
        agencyCode: "IRS",
        name: "Internal Revenue Service",
        jurisdictionType: "federal",
        jurisdictionCode: "US",
        status: "active",
        actorAdminId: 42,
      });

      const registration = await createTaxRegistration(repo, {
        legalEntityId: 1,
        taxAgencyId: agency.id,
        taxType: "federal_withholding",
        jurisdictionType: "federal",
        jurisdictionCode: "US",
        maskedAccountRef: "****9999",
        effectiveFrom: "2026-01-01",
        status: "active",
        notes: "manual registration",
        actorAdminId: 42,
      });

      await assert.rejects(
        () => createTaxRegistration(repo, {
          legalEntityId: 1,
          taxAgencyId: agency.id,
          taxType: "federal_withholding",
          jurisdictionType: "federal",
          jurisdictionCode: "US",
          effectiveFrom: "2026-02-01",
          status: "active",
          actorAdminId: 42,
        }),
        (error) => error instanceof TaxServiceError && error.code === "TAX_REGISTRATION_OVERLAP",
      );

      const liability = await createTaxLiability(repo, {
        taxRegistrationId: registration!.id,
        periodStart: "2026-04-01",
        periodEnd: "2026-06-30",
        dueDate: "2026-07-31",
        component: "withholding",
        amountCents: 10_626,
        currency: "USD",
        sourceType: "manual",
        sourceMetadata: { providerBatch: "raw" },
        actorAdminId: 42,
      });
      await transitionTaxLiability(repo, liability.id, { status: "recognized", actorAdminId: 42 });

      const adjustment = await createTaxLiabilityAdjustment(repo, liability.id, {
        amountEffect: "decrease",
        amountCents: 26,
        actorAdminId: 42,
      });
      await transitionTaxLiability(repo, adjustment.id, { status: "recognized", actorAdminId: 42 });

      const payment = await recordTaxAgencyPayment(repo, {
        taxRegistrationId: registration!.id,
        amountCents: 10_600,
        currency: "USD",
        paymentDate: "2026-07-15",
        methodType: "ach",
        methodLabel: "ACH",
        institutionName: "Bank",
        maskedLast4: "1234",
        confirmationRef: "IRS-10600",
        status: "cleared",
        actorAdminId: 42,
      });

      const allocation = await applyTaxPaymentAllocation(repo, {
        taxLiabilityId: liability.id,
        taxAgencyPaymentId: payment.id,
        amountCents: 10_600,
        currency: "USD",
        actorAdminId: 42,
      });
      assert.equal(allocation.status, "active");

      await assert.rejects(
        () => applyTaxPaymentAllocation(repo, {
          taxLiabilityId: liability.id,
          taxAgencyPaymentId: payment.id,
          amountCents: 1,
          currency: "USD",
          actorAdminId: 42,
        }),
        (error) => (
          error instanceof TaxServiceError
          && error.code === "TAX_ALLOCATION_ACTIVE_PAIR_EXISTS"
        ),
      );
      const allocationsAfterDuplicate = await client.query(
        `SELECT count(*)::int AS "count" FROM "tax_payment_allocations" WHERE "status" = 'active'`,
      );
      assert.equal(allocationsAfterDuplicate.rows[0].count, 1);

      const reversedAllocation = await reverseTaxPaymentAllocation(repo, allocation.id, 42);
      assert.equal(reversedAllocation.status, "reversed");
      const reversedPayment = await reverseTaxAgencyPayment(repo, payment.id, 42);
      assert.equal(reversedPayment.status, "reversed");

      const filing = await createTaxFiling(repo, {
        taxRegistrationId: registration!.id,
        filingType: "941",
        periodStart: "2026-04-01",
        periodEnd: "2026-06-30",
        dueDate: "2026-07-31",
        actorAdminId: 42,
      });
      await transitionTaxFiling(repo, filing.id, { status: "ready", actorAdminId: 42 });
      await transitionTaxFiling(repo, filing.id, {
        status: "filed",
        confirmationRef: "IRS-941-2026Q2",
        actorAdminId: 42,
      });
      await transitionTaxFiling(repo, filing.id, { status: "accepted", actorAdminId: 42 });
      const filingAmendment = await createTaxFilingAmendment(repo, filing.id, {
        notes: "manual amendment tracking only",
        actorAdminId: 42,
      });
      assert.equal(filingAmendment.amendsTaxFilingId, filing.id);

      const exception = await createTaxReconciliationException(repo, {
        expectedEntityType: "tax_liabilities",
        expectedEntityId: liability.id,
        actualEntityType: "tax_agency_payments",
        actualEntityId: payment.id,
        expectedAmountCents: 10_626,
        actualAmountCents: 10_600,
        currency: "USD",
        reasonCode: "tax_underpayment",
        summary: "Q2 liability remains underpaid by 26 cents.",
        actorAdminId: 42,
      });
      await transitionTaxReconciliationException(repo, exception.id, "resolve", {
        resolutionNotes: "Agency credit posted",
        actorAdminId: 42,
      });

      const ref = await createTaxExternalRecordRef(repo, {
        entityType: "tax_filings",
        entityId: filing.id,
        sourceType: "provider",
        sourceVendorId: 20,
        sourceNamespace: "provider",
        externalRecordType: "filing",
        externalRecordId: "provider-filing-123",
        payloadHash: "abc123",
        metadata: { rawPayload: "not returned by DTO" },
        status: "active",
        actorAdminId: 42,
      });
      assert.equal(ref.externalRecordId, "provider-filing-123");

      const payrollRows = await client.query(`SELECT count(*)::int AS "count" FROM "payroll_runs"`);
      const apRows = await client.query(`SELECT count(*)::int AS "count" FROM "vendor_bills"`);
      assert.equal(payrollRows.rows[0].count, 0);
      assert.equal(apRows.rows[0].count, 0);

      const auditEvents = await client.query<{ entity_type: string; action: string }>(
        `SELECT "entity_type", "action" FROM "tax_audit_events" ORDER BY "id"`,
      );
      assert.deepEqual(
        auditEvents.rows.map((row) => `${row.entity_type}:${row.action}`),
        [
          "tax_agency:created",
          "tax_registration:created",
          "tax_liability:created",
          "tax_liability:recognized",
          "tax_liability:adjustment_created",
          "tax_liability:recognized",
          "tax_agency_payment:created",
          "tax_payment_allocation:allocation_created",
          "tax_payment_allocation:reversed",
          "tax_agency_payment:reversed",
          "tax_filing:created",
          "tax_filing:ready",
          "tax_filing:filed",
          "tax_filing:accepted",
          "tax_filing:amendment_created",
          "reconciliation_exception:created",
          "reconciliation_exception:resolved",
        ],
      );
    });
  },
);
