import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

import { createPostgresPool } from "../../db-client";
import {
  canonicalSqlSha256,
  getMigrationStatus,
  parseMigrationFilename,
  runMigrations,
  type MigrationFile,
} from "../../../scripts/migrationRunner";

const POSTGRES_TEST_DATABASE_URL = process.env.MIGRATION_RUNNER_TEST_DATABASE_URL;

const EXISTING_GRANTS = [
  "finance_admin",
  "verifier_admin",
  "support_admin",
  "super_admin",
  "admin_operations",
  "trainee_offer_portal",
  "trainee_workspace",
  "document_templates",
  "lifecycle_jobs",
] as const;

function assertDisposablePostgresTestUrl(connectionString: string) {
  let databaseName = "";
  try {
    const parsed = new URL(connectionString.replace(/^postgres:\/\//, "postgresql://"));
    databaseName = decodeURIComponent(parsed.pathname.replace(/^\//, ""));
  } catch {
    throw new Error("MIGRATION_RUNNER_TEST_DATABASE_URL must be a valid PostgreSQL URL.");
  }

  if (!/(test|tmp|scratch|disposable|codex)/i.test(databaseName)) {
    throw new Error(
      "MIGRATION_RUNNER_TEST_DATABASE_URL must point to a disposable database whose name contains test, tmp, scratch, disposable, or codex.",
    );
  }
}

function migration(filename: string, sql: string): MigrationFile {
  return {
    filename,
    version: parseMigrationFilename(filename),
    checksumSha256: canonicalSqlSha256(sql),
    sql,
  };
}

function readPayrollGrantMigration() {
  return readFileSync(
    new URL("../../../migrations/0026_admin_payroll_access_grant.sql", import.meta.url),
    "utf8",
  );
}

async function createEmptyMigrationLedger(client: {
  query(sql: string, params?: unknown[]): Promise<unknown>;
}) {
  await client.query(`
    CREATE TABLE public."schema_migrations" (
      "filename" text PRIMARY KEY,
      "checksum_sha256" text NOT NULL,
      "applied_at" timestamptz NOT NULL DEFAULT now(),
      "execution_ms" integer,
      "application_mode" text NOT NULL,
      CONSTRAINT "schema_migrations_checksum_sha256_check"
        CHECK ("checksum_sha256" ~ '^[0-9a-f]{64}$'),
      CONSTRAINT "schema_migrations_execution_ms_check"
        CHECK ("execution_ms" IS NULL OR "execution_ms" >= 0),
      CONSTRAINT "schema_migrations_application_mode_check"
        CHECK ("application_mode" IN ('applied', 'adopted', 'baseline'))
    )
  `);
}

test("0026 payroll access-grant migration only extends the access grant vocabulary", () => {
  const migrationSql = readPayrollGrantMigration();

  assert.match(migrationSql, /DROP CONSTRAINT IF EXISTS "admin_user_access_grants_access_group_check"/);
  assert.match(migrationSql, /ADD CONSTRAINT "admin_user_access_grants_access_group_check"/);
  assert.match(migrationSql, /'payroll_admin'/);
  assert.doesNotMatch(migrationSql, /\bUPDATE\b|\bDELETE\b|\bDROP TABLE\b|\bCREATE TABLE\b/i);
});

test(
  "0026 payroll access-grant migration preserves existing grants and admits payroll_admin on disposable PostgreSQL",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    assert.ok(POSTGRES_TEST_DATABASE_URL);
    assertDisposablePostgresTestUrl(POSTGRES_TEST_DATABASE_URL);

    const pool = createPostgresPool(POSTGRES_TEST_DATABASE_URL, {
      sslEnvNames: ["MIGRATION_RUNNER_TEST_DB_SSL", "DB_SSL"],
    });
    const setupSql = `
      CREATE TABLE "admin_users" (
        "id" integer PRIMARY KEY,
        "email" text NOT NULL
      );

      CREATE TABLE "admin_user_access_grants" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "admin_user_id" integer NOT NULL,
        "access_group" text NOT NULL,
        "source" text,
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "granted_by" integer,
        "granted_at" timestamp NOT NULL DEFAULT now(),
        "revoked_by" integer,
        "revoked_at" timestamp,
        "created_at" timestamp DEFAULT now(),
        "updated_at" timestamp DEFAULT now(),
        CONSTRAINT "admin_user_access_grants_access_group_check"
          CHECK ("access_group" IN (
            'finance_admin',
            'verifier_admin',
            'support_admin',
            'super_admin',
            'admin_operations',
            'trainee_offer_portal',
            'trainee_workspace',
            'document_templates',
            'lifecycle_jobs'
          ))
      );

      INSERT INTO "admin_users" ("id", "email")
      VALUES (1, 'owner@example.com');
    `;

    try {
      const client = await pool.connect();
      try {
        await client.query(`DROP TABLE IF EXISTS public."admin_user_access_grants" CASCADE`);
        await client.query(`DROP TABLE IF EXISTS public."admin_users" CASCADE`);
        await client.query(`DROP TABLE IF EXISTS public."schema_migrations" CASCADE`);
        await createEmptyMigrationLedger(client);
      } finally {
        client.release();
      }

      const setupMigration = migration("0001_stage8_payroll_access_grant_setup.sql", setupSql);
      const payrollGrantMigration = migration(
        "0026_admin_payroll_access_grant.sql",
        readPayrollGrantMigration(),
      );
      const result = await runMigrations(pool, [setupMigration, payrollGrantMigration]);
      assert.deepEqual(result.applied, [
        setupMigration.filename,
        payrollGrantMigration.filename,
      ]);
      assert.deepEqual(result.pendingBeforeRun, [
        setupMigration.filename,
        payrollGrantMigration.filename,
      ]);

      const writeClient = await pool.connect();
      try {
        for (const [index, grant] of EXISTING_GRANTS.entries()) {
          await writeClient.query(
            `INSERT INTO "admin_user_access_grants" ("admin_user_id", "access_group") VALUES (1, $1)`,
            [grant],
          );
          const row = await writeClient.query<{ access_group: string }>(
            `SELECT "access_group" FROM "admin_user_access_grants" WHERE "id" = $1`,
            [index + 1],
          );
          assert.equal(row.rows[0]?.access_group, grant);
        }

        await writeClient.query(
          `INSERT INTO "admin_user_access_grants" ("admin_user_id", "access_group") VALUES (1, 'payroll_admin')`,
        );

        await assert.rejects(
          writeClient.query(
            `INSERT INTO "admin_user_access_grants" ("admin_user_id", "access_group") VALUES (1, 'random_grant')`,
          ),
          /violates check constraint/,
        );

        const grants = await writeClient.query<{ access_group: string }>(
          `SELECT "access_group" FROM "admin_user_access_grants" ORDER BY "id"`,
        );
        assert.deepEqual(
          grants.rows.map((row) => row.access_group),
          [...EXISTING_GRANTS, "payroll_admin"],
        );
      } finally {
        writeClient.release();
      }

      const status = await getMigrationStatus(pool, [setupMigration, payrollGrantMigration]);
      assert.equal(status.ledgerPresent, true);
      assert.equal(status.ledgeredMigrationCount, 2);
      assert.equal(status.latestLedgeredMigration, payrollGrantMigration.filename);
      assert.deepEqual(status.pendingMigrations, []);
      assert.deepEqual(status.checksumMismatches, []);
      assert.deepEqual(status.orderingProblems, []);
    } finally {
      const cleanup = await pool.connect();
      try {
        await cleanup.query(`DROP TABLE IF EXISTS public."admin_user_access_grants" CASCADE`);
        await cleanup.query(`DROP TABLE IF EXISTS public."admin_users" CASCADE`);
        await cleanup.query(`DROP TABLE IF EXISTS public."schema_migrations" CASCADE`);
      } finally {
        cleanup.release();
        await pool.end();
      }
    }
  },
);
