import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { drizzle } from "drizzle-orm/node-postgres";
import type { PoolClient } from "pg";

import { createPostgresPool } from "../../db-client";
import {
  PayrollServiceError,
  addPayrollResultLine,
  addPayrollRunWorker,
  createPayrollCorrectionRun,
  createPayrollExternalRecordRef,
  createPayrollRun,
  finalizePayrollRun,
  markPayrollRunReviewed,
  recordPayrollPayment,
  reversePayrollPayment,
  transitionPayrollPayment,
} from "../../payrollService";
import { createPayrollRepository } from "../../payrollRepositoryFactory";

const POSTGRES_TEST_DATABASE_URL = process.env.MIGRATION_RUNNER_TEST_DATABASE_URL;

function assertDisposablePostgresTestUrl(connectionString: string) {
  let databaseName = "";
  try {
    const parsed = new URL(connectionString.replace(/^postgres:\/\//, "postgresql://"));
    databaseName = decodeURIComponent(parsed.pathname.replace(/^\//, ""));
  } catch {
    throw new Error("MIGRATION_RUNNER_TEST_DATABASE_URL must be a valid PostgreSQL URL.");
  }

  if (!/(test|tmp|scratch|disposable|codex)/i.test(databaseName)) {
    throw new Error(
      "MIGRATION_RUNNER_TEST_DATABASE_URL must point to a disposable database whose name contains test, tmp, scratch, disposable, or codex.",
    );
  }
}

function testSchemaName() {
  return `stage8_payroll_${process.pid}_${randomUUID().replace(/-/g, "").slice(0, 12)}`;
}

async function createPayrollTables(client: PoolClient) {
  await client.query(`
    CREATE TABLE "legal_entities" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "legal_name" text NOT NULL,
      "entity_type" text NOT NULL DEFAULT 'llc',
      "formation_state" text,
      "masked_tax_identifier" text,
      "status" text NOT NULL DEFAULT 'active',
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "vendors" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "name" text NOT NULL,
      "vendor_type" text NOT NULL DEFAULT 'other',
      "status" text NOT NULL DEFAULT 'active',
      "website" text,
      "contact_email" text,
      "notes" text,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "workers" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "admin_user_id" integer,
      "worker_code" text NOT NULL,
      "legal_name" text NOT NULL,
      "preferred_name" text,
      "personnel_email" text,
      "archived_at" timestamp,
      "voided_at" timestamp,
      "merged_into_worker_id" integer,
      "merged_at" timestamp,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "employments" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "worker_id" integer NOT NULL,
      "legal_entity_id" integer NOT NULL,
      "employee_classification" text NOT NULL DEFAULT 'employee',
      "payroll_participation" text NOT NULL DEFAULT 'not_enrolled',
      "status" text NOT NULL DEFAULT 'draft',
      "start_date" date NOT NULL,
      "end_date" date,
      "work_location" text,
      "primary_work_state" text,
      "primary_work_jurisdiction" text,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "payroll_runs" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "legal_entity_id" integer NOT NULL,
      "period_start" date NOT NULL,
      "period_end" date NOT NULL,
      "pay_date" date NOT NULL,
      "run_kind" text NOT NULL DEFAULT 'regular',
      "source_type" text NOT NULL DEFAULT 'manual',
      "source_vendor_id" integer,
      "correction_of_payroll_run_id" integer,
      "status" text NOT NULL DEFAULT 'draft',
      "finalized_at" timestamp,
      "finalized_by" integer,
      "notes" text,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "payroll_run_workers" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "payroll_run_id" integer NOT NULL,
      "worker_id" integer NOT NULL,
      "employment_id" integer NOT NULL,
      "currency" text NOT NULL DEFAULT 'USD',
      "gross_pay_cents" integer NOT NULL DEFAULT 0,
      "employee_tax_cents" integer NOT NULL DEFAULT 0,
      "employer_tax_cents" integer NOT NULL DEFAULT 0,
      "deduction_cents" integer NOT NULL DEFAULT 0,
      "net_pay_cents" integer NOT NULL DEFAULT 0,
      "source_metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE UNIQUE INDEX "idx_payroll_run_workers_run_employment_unique"
      ON "payroll_run_workers" ("payroll_run_id", "employment_id");

    CREATE TABLE "payroll_result_lines" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "payroll_run_worker_id" integer NOT NULL,
      "line_category" text NOT NULL,
      "line_code" text NOT NULL,
      "description" text,
      "amount_effect" text NOT NULL DEFAULT 'increase',
      "amount_cents" integer NOT NULL,
      "currency" text NOT NULL DEFAULT 'USD',
      "quantity_microunits" integer,
      "rate_amount_cents" integer,
      "jurisdiction_code" text,
      "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "payroll_payments" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "payroll_run_worker_id" integer NOT NULL,
      "amount_cents" integer NOT NULL,
      "currency" text NOT NULL DEFAULT 'USD',
      "payment_date" date,
      "method_type" text NOT NULL,
      "method_label" text,
      "institution_name" text,
      "masked_last4" text,
      "external_confirmation_ref" text,
      "status" text NOT NULL DEFAULT 'pending',
      "processed_at" timestamp,
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "payroll_audit_events" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "actor_admin_user_id" integer NOT NULL,
      "entity_type" text NOT NULL,
      "entity_id" integer NOT NULL,
      "action" text NOT NULL,
      "changes_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
      "created_at" timestamp DEFAULT now()
    );

    CREATE TABLE "external_record_refs" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "entity_type" text NOT NULL,
      "entity_id" integer NOT NULL,
      "source_type" text NOT NULL,
      "source_vendor_id" integer,
      "source_namespace" text NOT NULL DEFAULT 'default',
      "external_record_type" text NOT NULL,
      "external_record_id" text NOT NULL,
      "imported_at" timestamp,
      "payload_hash" text,
      "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
      "status" text NOT NULL DEFAULT 'active',
      "created_by" integer,
      "created_at" timestamp DEFAULT now(),
      "updated_at" timestamp DEFAULT now()
    );

    CREATE TABLE "tax_liabilities" (
      "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    );
  `);
}

async function seedPayrollReferences(client: PoolClient) {
  await client.query(`
    INSERT INTO "legal_entities" ("id", "legal_name", "status")
    VALUES (1, 'Test LLC', 'active');

    INSERT INTO "vendors" ("id", "name", "vendor_type", "status")
    VALUES (20, 'Payroll Provider', 'payroll_provider', 'active');

    INSERT INTO "workers" ("id", "worker_code", "legal_name", "personnel_email")
    VALUES (100, 'W-100', 'Jane Worker', 'private-worker@example.com');

    INSERT INTO "employments"
      ("id", "worker_id", "legal_entity_id", "employee_classification", "payroll_participation", "status", "start_date", "work_location", "primary_work_state")
    VALUES
      (200, 100, 1, 'employee', 'active', 'active', '2026-01-01', 'private location', 'MI');
  `);
}

async function withPayrollSchema<T>(
  work: (client: PoolClient, schemaName: string) => Promise<T>,
) {
  assert.ok(POSTGRES_TEST_DATABASE_URL);
  assertDisposablePostgresTestUrl(POSTGRES_TEST_DATABASE_URL);
  const pool = createPostgresPool(POSTGRES_TEST_DATABASE_URL, {
    sslEnvNames: ["MIGRATION_RUNNER_TEST_DB_SSL", "DB_SSL"],
  });
  const client = await pool.connect();
  const schemaName = testSchemaName();

  try {
    await client.query(`CREATE SCHEMA "${schemaName}"`);
    await client.query(`SET search_path TO "${schemaName}", public`);
    await createPayrollTables(client);
    await seedPayrollReferences(client);
    return await work(client, schemaName);
  } finally {
    await client.query(`DROP SCHEMA IF EXISTS "${schemaName}" CASCADE`).catch(() => undefined);
    client.release();
    await pool.end();
  }
}

function repoForClient(client: PoolClient) {
  return createPayrollRepository(drizzle(client));
}

test(
  "V2 Payroll repository preserves transaction rollback when audit insert fails on disposable PostgreSQL",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    await withPayrollSchema(async (client) => {
      await client.query(`ALTER TABLE "payroll_audit_events" ADD CONSTRAINT "reject_created_audit" CHECK ("action" <> 'created')`);
      const repo = repoForClient(client);

      await assert.rejects(
        () => createPayrollRun(repo, {
          legalEntityId: 1,
          periodStart: "2026-01-01",
          periodEnd: "2026-01-15",
          payDate: "2026-01-20",
          runKind: "regular",
          sourceType: "manual",
          actorAdminId: 42,
        }),
        /violates check constraint/,
      );

      const runs = await client.query(`SELECT "id" FROM "payroll_runs"`);
      const auditEvents = await client.query(`SELECT "id" FROM "payroll_audit_events"`);
      assert.equal(runs.rowCount, 0);
      assert.equal(auditEvents.rowCount, 0);
    });
  },
);

test(
  "V2 Payroll repository locks payroll runs with SELECT FOR UPDATE on the same transaction connection",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    assert.ok(POSTGRES_TEST_DATABASE_URL);
    assertDisposablePostgresTestUrl(POSTGRES_TEST_DATABASE_URL);
    const pool = createPostgresPool(POSTGRES_TEST_DATABASE_URL, {
      sslEnvNames: ["MIGRATION_RUNNER_TEST_DB_SSL", "DB_SSL"],
    });
    const clientA = await pool.connect();
    const clientB = await pool.connect();
    const schemaName = testSchemaName();
    let releaseTransaction!: () => void;
    const holdTransaction = new Promise<void>((resolve) => {
      releaseTransaction = resolve;
    });
    let locked!: () => void;
    const lockAcquired = new Promise<void>((resolve) => {
      locked = resolve;
    });

    try {
      await clientA.query(`CREATE SCHEMA "${schemaName}"`);
      await clientA.query(`SET search_path TO "${schemaName}", public`);
      await createPayrollTables(clientA);
      await seedPayrollReferences(clientA);
      await clientA.query(`
        INSERT INTO "payroll_runs"
          ("id", "legal_entity_id", "period_start", "period_end", "pay_date", "run_kind", "source_type", "status")
        VALUES (300, 1, '2026-01-01', '2026-01-15', '2026-01-20', 'regular', 'manual', 'draft')
      `);
      await clientB.query(`SET search_path TO "${schemaName}", public`);
      await clientB.query(`SET lock_timeout TO '100ms'`);

      const repo = repoForClient(clientA);
      const transaction = repo.transaction(async (tx) => {
        await tx.lockPayrollRun(300);
        locked();
        await holdTransaction;
      });

      await lockAcquired;
      await assert.rejects(
        () => clientB.query(`UPDATE "payroll_runs" SET "notes" = 'blocked' WHERE "id" = 300`),
        (error: unknown) => typeof error === "object" && error !== null && "code" in error && error.code === "55P03",
      );

      releaseTransaction();
      await transaction;
    } finally {
      releaseTransaction();
      await clientA.query(`DROP SCHEMA IF EXISTS "${schemaName}" CASCADE`).catch(() => undefined);
      clientA.release();
      clientB.release();
      await pool.end();
    }
  },
);

test(
  "V2 Payroll disposable PostgreSQL path preserves lifecycle, payments, corrections, audit, and Tax isolation",
  {
    skip: POSTGRES_TEST_DATABASE_URL
      ? false
      : "Set MIGRATION_RUNNER_TEST_DATABASE_URL to a disposable PostgreSQL database to run.",
  },
  async () => {
    await withPayrollSchema(async (client) => {
      const repo = repoForClient(client);

      const run = await createPayrollRun(repo, {
        legalEntityId: 1,
        periodStart: "2026-01-01",
        periodEnd: "2026-01-15",
        payDate: "2026-01-20",
        runKind: "regular",
        sourceType: "provider",
        sourceVendorId: 20,
        actorAdminId: 42,
      });
      const runWorker = await addPayrollRunWorker(repo, run.id, {
        workerId: 100,
        employmentId: 200,
        currency: "USD",
        grossPayCents: 100_000,
        employeeTaxCents: 20_000,
        employerTaxCents: 8_000,
        deductionCents: 5_000,
        netPayCents: 75_000,
        sourceMetadata: { providerBatch: "batch-1" },
        actorAdminId: 42,
      });

      await assert.rejects(
        () => addPayrollRunWorker(repo, run.id, {
          workerId: 100,
          employmentId: 200,
          currency: "USD",
          grossPayCents: 100_000,
          employeeTaxCents: 20_000,
          employerTaxCents: 8_000,
          deductionCents: 5_000,
          netPayCents: 75_000,
          sourceMetadata: {},
          actorAdminId: 42,
        }),
        (error) => error instanceof PayrollServiceError && error.code === "PAYROLL_RUN_WORKER_DUPLICATE",
      );

      await addPayrollResultLine(repo, runWorker.id, {
        lineCategory: "employee_tax",
        lineCode: "FEDERAL_INCOME_TAX",
        amountEffect: "increase",
        amountCents: 20_000,
        currency: "USD",
        jurisdictionCode: "US-FED",
        metadata: {},
        actorAdminId: 42,
      });
      await addPayrollResultLine(repo, runWorker.id, {
        lineCategory: "employer_tax",
        lineCode: "FICA_ER",
        amountEffect: "increase",
        amountCents: 8_000,
        currency: "USD",
        jurisdictionCode: "US-FED",
        metadata: {},
        actorAdminId: 42,
      });

      await markPayrollRunReviewed(repo, run.id, 42);
      await finalizePayrollRun(repo, run.id, 42, new Date("2026-01-20T12:00:00.000Z"));

      const payment = await recordPayrollPayment(repo, runWorker.id, {
        amountCents: 75_000,
        currency: "USD",
        methodType: "manual",
        status: "pending",
        actorAdminId: 42,
      });
      await assert.rejects(
        () => transitionPayrollPayment(repo, payment.id, {
          status: "cleared",
          paymentDate: "2026-01-20",
          actorAdminId: 42,
        }),
        (error) => error instanceof PayrollServiceError && error.code === "PAYROLL_PAYMENT_TRANSITION_INVALID",
      );
      await transitionPayrollPayment(repo, payment.id, {
        status: "sent",
        paymentDate: "2026-01-20",
        actorAdminId: 42,
      });
      await transitionPayrollPayment(repo, payment.id, {
        status: "cleared",
        paymentDate: "2026-01-20",
        actorAdminId: 42,
      });
      await reversePayrollPayment(repo, payment.id, 42, new Date("2026-01-21T12:00:00.000Z"));

      const ref = await createPayrollExternalRecordRef(repo, {
        entityType: "payroll_runs",
        entityId: run.id,
        sourceType: "provider",
        sourceVendorId: 20,
        sourceNamespace: "payroll",
        externalRecordType: "payroll_run",
        externalRecordId: "provider-run-123",
        metadata: {},
        status: "active",
        actorAdminId: 42,
      });
      assert.equal(ref.externalRecordId, "provider-run-123");

      const correction = await createPayrollCorrectionRun(repo, {
        correctionOfPayrollRunId: run.id,
        periodStart: "2026-01-01",
        periodEnd: "2026-01-15",
        payDate: "2026-01-31",
        sourceType: "manual",
        actorAdminId: 42,
      });
      assert.equal(correction.runKind, "correction");

      const taxRows = await client.query(`SELECT count(*)::int AS "count" FROM "tax_liabilities"`);
      assert.equal(taxRows.rows[0].count, 0);

      const auditEvents = await client.query<{ entity_type: string; action: string }>(
        `SELECT "entity_type", "action" FROM "payroll_audit_events" ORDER BY "id"`,
      );
      assert.deepEqual(
        auditEvents.rows.map((row) => `${row.entity_type}:${row.action}`),
        [
          "payroll_run:created",
          "payroll_run_worker:created",
          "payroll_result_line:created",
          "payroll_result_line:created",
          "payroll_run:reviewed",
          "payroll_run:finalized",
          "payroll_payment:recorded",
          "payroll_payment:sent",
          "payroll_payment:cleared",
          "payroll_payment:reversed",
          "payroll_run:correction_created",
        ],
      );
    });
  },
);
